name: ocr
channels: 
  - default
dependencies:
  - python=3.8
  - pandas=1.1.0
  - pip
  - pip:
      - pytesseract
      - opencv-python
      - nltk
      - matplotlib
      - wordcloud
      - gtts
