name: fastapi-demo
channels: 
  - default
dependencies:
  - python=3.7.5
  - pandas=1.1.0
  - pip
  - pip:
      - fastapi==0.61.1
      - uvicorn==0.11.8
      - codetiming==1.2.0
      - requests
      - databases==0.3.2
      - databases[postgresql]
      - asyncpg==0.21.0